{% set name = "acorns" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deshanadesai/acorns/archive/{{ version }}.tar.gz
  sha256: 06d586aa34cfc32296a067d861bcda152f4a9ac4040b30eb8ddf42393a50e575

build:
  number: 0
  noarch: python 
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - pycparser
    - numpy

test:
  imports:
    - acorns

about:
  home: https://github.com/deshanadesai/acorns
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An Easy-To-Use Code Generator for Gradients and Hessians

  description: |
    ACORNS is an algorithm for automatic differention of algorithms 
    written in a subset of C99 code and its efficient implementation as a Python script. 
  dev_url: https://github.com/deshanadesai/acorns

extra:
  recipe-maintainers:
    - DeshanaDesai
