{% set name = "acorns" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deshanadesai/acorns/archive/{{ version }}.tar.gz
  sha256: 114d4ea68eb2c7aa978d82b46c602d9efb9019ed39c1aa8fb362b87037723285

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pycparser
    - numpy

test:
  imports:
    - acorns

about:
  home: https://github.com/deshanadesai/acorns
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An Easy-To-Use Code Generator for Gradients and Hessians

  description: |
    ACORNS is an algorithm for automatic differention of algorithms 
    written in a subset of C99 code and its efficient implementation as a Python script. 
  dev_url: https://github.com/deshanadesai/acorns

extra:
  recipe-maintainers:
    - DeshanaDesai
