{% set name = "acorns" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deshanadesai/autodiff/archive/v{{ version }}.tar.gz
  sha256: 1c9ff852f2bf65b0db20da5b25f44c24c262cfcc06c5fd8d0fe11055a742f685

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pycparser
    - numpy

test:
  imports:
    - acorns

about:
  home: https://github.com/deshanadesai/acorns
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An Easy-To-Use Code Generator for Gradients and Hessians

  description: |
    ACORNS is an algorithm for automatic differention of algorithms 
    written in a subset of C99 code and its efficient implementation as a Python script. 
  dev_url: https://github.com/deshanadesai/acorns

extra:
  recipe-maintainers:
    - DeshanaDesai
